//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorClient.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to активних підписок.
        /// </summary>
        public static string ActiveSubscriptionsLabel {
            get {
                return ResourceManager.GetString("ActiveSubscriptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уникати.
        /// </summary>
        public static string Avoid {
            get {
                return ResourceManager.GetString("Avoid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Будматеріали.
        /// </summary>
        public static string BuildingMaterials {
            get {
                return ResourceManager.GetString("BuildingMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купувати зараз.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Календар.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорії.
        /// </summary>
        public static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категорії ще не додані.
        /// </summary>
        public static string CategoriesYetEmpty {
            get {
                return ResourceManager.GetString("CategoriesYetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірте з&apos;єднання з інтернетом і спробуйте ще раз..
        /// </summary>
        public static string CheckInternetAndTryAgain {
            get {
                return ResourceManager.GetString("CheckInternetAndTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оберіть товар, і ми покажемо, коли його найвигідніше купувати.
        /// </summary>
        public static string ChooseProductForBestBuy {
            get {
                return ResourceManager.GetString("ChooseProductForBestBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка завантаження.
        /// </summary>
        public static string ErrorLoading {
            get {
                return ResourceManager.GetString("ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка завантаження категорій.
        /// </summary>
        public static string ErrorLoadingCategories {
            get {
                return ResourceManager.GetString("ErrorLoadingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не вдалося завантажити дані.
        /// </summary>
        public static string FailedToLoadData {
            get {
                return ResourceManager.GetString("FailedToLoadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активні.
        /// </summary>
        public static string FilterActive {
            get {
                return ResourceManager.GetString("FilterActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Усі.
        /// </summary>
        public static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Призупинені.
        /// </summary>
        public static string FilterPaused {
            get {
                return ResourceManager.GetString("FilterPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дрова.
        /// </summary>
        public static string Firewood {
            get {
                return ResourceManager.GetString("Firewood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дрова • Волинська область.
        /// </summary>
        public static string FirewoodOakSubtitle {
            get {
                return ResourceManager.GetString("FirewoodOakSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Колоті дрова, дуб.
        /// </summary>
        public static string FirewoodOakTitle {
            get {
                return ResourceManager.GetString("FirewoodOakTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пальне.
        /// </summary>
        public static string Fuel {
            get {
                return ResourceManager.GetString("Fuel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажуємо ціни....
        /// </summary>
        public static string LoadingPrices {
            get {
                return ResourceManager.GetString("LoadingPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажуємо підписки....
        /// </summary>
        public static string LoadingSubscriptions {
            get {
                return ResourceManager.GetString("LoadingSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кві.
        /// </summary>
        public static string Month_Apr {
            get {
                return ResourceManager.GetString("Month_Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сер.
        /// </summary>
        public static string Month_Aug {
            get {
                return ResourceManager.GetString("Month_Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гру.
        /// </summary>
        public static string Month_Dec {
            get {
                return ResourceManager.GetString("Month_Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лют.
        /// </summary>
        public static string Month_Feb {
            get {
                return ResourceManager.GetString("Month_Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Січ.
        /// </summary>
        public static string Month_Jan {
            get {
                return ResourceManager.GetString("Month_Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лип.
        /// </summary>
        public static string Month_Jul {
            get {
                return ResourceManager.GetString("Month_Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чер.
        /// </summary>
        public static string Month_Jun {
            get {
                return ResourceManager.GetString("Month_Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бер.
        /// </summary>
        public static string Month_Mar {
            get {
                return ResourceManager.GetString("Month_Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Трв.
        /// </summary>
        public static string Month_May {
            get {
                return ResourceManager.GetString("Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лис.
        /// </summary>
        public static string Month_Nov {
            get {
                return ResourceManager.GetString("Month_Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Жов.
        /// </summary>
        public static string Month_Oct {
            get {
                return ResourceManager.GetString("Month_Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вер.
        /// </summary>
        public static string Month_Sep {
            get {
                return ResourceManager.GetString("Month_Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квітень.
        /// </summary>
        public static string MonthApril {
            get {
                return ResourceManager.GetString("MonthApril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мої підписки.
        /// </summary>
        public static string MySubscriptions {
            get {
                return ResourceManager.GetString("MySubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нових сповіщення.
        /// </summary>
        public static string NewNotificationsLabel {
            get {
                return ResourceManager.GetString("NewNotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найближче сповіщення.
        /// </summary>
        public static string NextNotification {
            get {
                return ResourceManager.GetString("NextNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дрова очікуємо на мінімумі; ціна впаде приблизно на {0}%.
        /// </summary>
        public static string NextNotificationText {
            get {
                return ResourceManager.GetString("NextNotificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поки що нічого не обрано.
        /// </summary>
        public static string NothingSelectedYet {
            get {
                return ResourceManager.GetString("NothingSelectedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ми напишемо, щойно індекс ціни опуститься нижче порога.
        /// </summary>
        public static string NotifyWhenIndexBelowThreshold {
            get {
                return ResourceManager.GetString("NotifyWhenIndexBelowThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сповістити, коли ціна знизиться.
        /// </summary>
        public static string NotifyWhenPriceDrops {
            get {
                return ResourceManager.GetString("NotifyWhenPriceDrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Індекс ціни з поправкою на інфляцію (100 = середня за рік).
        /// </summary>
        public static string PriceIndexNote {
            get {
                return ResourceManager.GetString("PriceIndexNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сповіщення про ціну.
        /// </summary>
        public static string PriceNotifications {
            get {
                return ResourceManager.GetString("PriceNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна впродовж року.
        /// </summary>
        public static string PriceThroughoutYear {
            get {
                return ResourceManager.GetString("PriceThroughoutYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна зростатиме ще приблизно на 14% до грудня.
        /// </summary>
        public static string PriceWillIncreaseText {
            get {
                return ResourceManager.GetString("PriceWillIncreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дрова, дуб.
        /// </summary>
        public static string ProductFirewoodOak {
            get {
                return ResourceManager.GetString("ProductFirewoodOak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шини.
        /// </summary>
        public static string ProductTires {
            get {
                return ResourceManager.GetString("ProductTires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Волинська область.
        /// </summary>
        public static string RegionVolyn {
            get {
                return ResourceManager.GetString("RegionVolyn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберегти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сезонні ціни.
        /// </summary>
        public static string SeasonalPrices {
            get {
                return ResourceManager.GetString("SeasonalPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ціна знизилась.
        /// </summary>
        public static string StatusPriceDropped {
            get {
                return ResourceManager.GetString("StatusPriceDropped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Чекаємо.
        /// </summary>
        public static string StatusWaiting {
            get {
                return ResourceManager.GetString("StatusWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підписатися.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підписки.
        /// </summary>
        public static string Subscriptions {
            get {
                return ResourceManager.GetString("Subscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram • {0} активних.
        /// </summary>
        public static string SubscriptionsTelegramActive {
            get {
                return ResourceManager.GetString("SubscriptionsTelegramActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це займе кілька секунд.
        /// </summary>
        public static string TakesFewSeconds {
            get {
                return ResourceManager.GetString("TakesFewSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тарифів.
        /// </summary>
        public static string TariffsLabel {
            get {
                return ResourceManager.GetString("TariffsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram або e-mail.
        /// </summary>
        public static string TelegramOrEmailPlaceholder {
            get {
                return ResourceManager.GetString("TelegramOrEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} • поріг: індекс ≤ {1}.
        /// </summary>
        public static string ThresholdLine {
            get {
                return ResourceManager.GetString("ThresholdLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шини.
        /// </summary>
        public static string Tires {
            get {
                return ResourceManager.GetString("Tires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спробувати ще раз.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вердикт на жовтень 2026.
        /// </summary>
        public static string VerdictOctober {
            get {
                return ResourceManager.GetString("VerdictOctober", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зачекати.
        /// </summary>
        public static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Куди надсилати сповіщення.
        /// </summary>
        public static string WhereToSendNotifications {
            get {
                return ResourceManager.GetString("WhereToSendNotifications", resourceCulture);
            }
        }
    }
}
